tests:
  username: User 
  password: Pass 
  site_address: https://commons.wikimedia.org/wiki/
  files:
    never_uploaded: /path/to/first/unique/file
    another_never_uploaded: /path/to/second/unique/file
