base_url:
  wikipedia: https://en.wikipedia.org/wiki/
  test: http://test.wikipedia.org/wiki/
  testm: http://test.m.wikipedia.org/w/index.php?title=
  test2: http://test2.wikipedia.org/wiki/
  wmflabs: http://en.wikipedia.beta.wmflabs.org/wiki/

android:
  platform: Linux
  version: 4

firefox:
  platform: Linux
  version: 16

internet_explorer:
  platform: Windows 2012
  version: 10

ipad:
  platform: Mac 10.6
  version: 5

iphone:
  platform: Mac 10.6
  version: 5
