base_url:
  local: http://127.0.0.1:8080/wiki/
  wikipedia: https://en.wikipedia.org/wiki/
  test: http://test.wikipedia.org/wiki/
  testm: http://test.m.wikipedia.org/w/index.php?title=
  test2: http://test2.wikipedia.org/wiki/
  wmflabs: http://en.wikipedia.beta.wmflabs.org/wiki/

mediawiki_username: uploadwizardtest

tests:
  site_address: https://test2.wikimedia.org/wiki/
  files:
    never_uploaded: /uwthumb2.png
    another_never_uploaded: /uwthumb1.png

android:
  name: android
  platform: Linux
  version: 4

chrome:
  name: chrome
  platform: Linux
  version:

firefox:
  name: firefox
  platform: Linux
  version: 16

internet_explorer_6:
  name: internet_explorer
  platform: Windows 2003
  version: 6

internet_explorer_7:
  name: internet_explorer
  platform: Windows 2003
  version: 7

internet_explorer_8:
  name: internet_explorer
  platform: Windows 2003
  version: 8

internet_explorer_9:
  name: internet_explorer
  platform: Windows 2008
  version: 9

internet_explorer_10:
  name: internet_explorer
  platform: Windows 2012
  version: 10

ipad:
  name: ipad
  platform: Mac 10.6
  version: 5

iphone:
  name: iphone
  platform: Mac 10.6
  version: 5
